### ISSUE TITLE
[Status Update]: Acord's Deprecation

### ISSUE THREAD

**Issue by kero3009destiny** [Discord-Client-Encyclopedia-Management/Discord3rdparties#100]
### Name

Acord

### Link

https://acord.app

### Development Status

Discontinued

### Further comments

Acord is currently on hiatus and will be discontinued on the next breaking Discord update that makes our current injection methods obsolete. Relevant (Turkish) update has also been announced on the official server.

**Comment by lexyclear** [comment]
noted
