### ISSUE TITLE
[Entry]: Vesktop

### ISSUE THREAD

**Issue by Koishukaze** [Discord-Client-Encyclopedia-Management/Discord3rdparties#102]
### Name

Vesktop

### Link

https://github.com/Vencord/Vesktop

### Features

Vesktop is a cross platform desktop app aiming to give you a snappier Discord experience with Vencord pre-installed

### Language(s)

Typescript

### Development Status

Active

**Comment by Jackgawe** [comment]
cool

**Comment by lexyclear** [comment]
We have officially added this.
