### ISSUE TITLE
Watch Clients

### ISSUE THREAD

**Issue by wont-stream** [Discord-Client-Encyclopedia-Management/Discord3rdparties#111]
### Describe your suggestion

Theres already mobile and desktop clients listed, I believe there should be a section for watches.

Here are a few
- https://apps.apple.com/us/app/watch-for-discord/id1552580781
- https://apps.apple.com/us/app/minicord/id1497954327

- https://play.google.com/store/apps/details?id=com.pixeldevelopers.minidiscord&hl=en

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by lexyclear** [comment]
these are not clients.

**Comment by wont-stream** [comment]
Mind explaining how, I‘m just a bit curious what is considered a „client“ in this context.
