### ISSUE TITLE
Discord x64

### ISSUE THREAD

**Issue by Mukul1127** [Discord-Client-Encyclopedia-Management/Discord3rdparties#112]
### Describe your suggestion

Discord now has PTB and Canary x64
![image](https://github.com/Discord-Client-Encyclopedia-Management/Discord3rdparties/assets/71291707/d7133c4b-d2d1-43b0-beee-e4b04fe94b4b)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by BNX070** [comment]
> ### Describe your suggestion
> 
> Discord now has PTB and Canary x64
> ![image](https://github.com/Discord-Client-Encyclopedia-Management/Discord3rdparties/assets/71291707/d7133c4b-d2d1-43b0-beee-e4b04fe94b4b)
> 
> 
> ### Acknowledgements
> 
> - [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> - [X] I have written a short but informative title.
> - [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
> - [X] I will fill out all of the requested information in this form.

Those are not 3rd parties

**Comment by daemonagentdev** [comment]
> > ### Describe your suggestion
> > Discord now has PTB and Canary x64
> > ![image](https://github.com/Discord-Client-Encyclopedia-Management/Discord3rdparties/assets/71291707/d7133c4b-d2d1-43b0-beee-e4b04fe94b4b)
> > ### Acknowledgements
> > 
> > * [x]  I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
> > * [x]  I have written a short but informative title.
> > * [ ]  I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
> > * [x]  I will fill out all of the requested information in this form.
> 
> Those are not 3rd parties

But the Repo list does contain the [offical clients](https://github.com/Discord-Client-Encyclopedia-Management/Discord3rdparties?tab=readme-ov-file#official-clients)
