### ISSUE TITLE
Acord automatically joins their support server upon client start.

### ISSUE THREAD

**Issue by eversiege** [Discord-Client-Encyclopedia-Management/Discord3rdparties#116]
### Describe your suggestion

I have used Acord because it was more stable than any other client I've tried. Overlooking the non-English installer, the client automatically joins their non-English server and rejoins every client restart (basically making this server unleavable)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by lexyclear** [comment]
This server is not for solving issues related to sus clients or client at all. go to those clients support servers.
also stop using acord.

**Comment by eversiege** [comment]
This was not made as a support ticket, just some info I had when I was using it. No need to be so rude.
