### ISSUE TITLE
Don't link to projects with bad/negative statuses

### ISSUE THREAD

**Issue by Andre601** [Discord-Client-Encyclopedia-Management/Discord3rdparties#122]
### Describe your suggestion

I feel like it's not a good practice to link to a project's website/source/whatever if it sdev status is not positive (i.e. malware, suspicious behaviour, etc).

It only results in them getting traffic from this list by curious people who want to know if what is stated is true.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by iProgramMC** [comment]
Question, what's wrong with Bluecord?

**Comment by Andre601** [comment]
Question: Why you ask in an unrelated PR?
Make an issue for this stuff to not annoy unrelated people... like me.

**Comment by iProgramMC** [comment]
My bad, I think I should have asked in the PR instead
