### ISSUE TITLE
[Entry]: Sunset

### ISSUE THREAD

**Issue by rezikham** [Discord-Client-Encyclopedia-Management/Discord3rdparties#126]
### Name

Sunset

### Link

https://github.com/sunset-mod/Sunset

### Features

A mod for @discord's mobile apps. Forked from Vendetta's recent sunset.

### Language(s)

Typescript, Javascript

### Development Status

Active

**Comment by hmm-monke** [comment]
sunset shouldve never been added

**Comment by rezikham** [comment]
Tbh i agree with u
