### ISSUE TITLE
[Entry]: Bunny

### ISSUE THREAD

**Issue by sehnryr** [Discord-Client-Encyclopedia-Management/Discord3rdparties#130]
### Name

Bunny

### Link

https://github.com/pyoncord/Bunny

### Features

A mod for Discord's mobile apps, fork of Vendetta.

### Language(s)

TypeScript

### Development Status

Active

### Further comments

From their `README.md`:
> [...] fork of Vendetta—from its contributor, *with an actual progress*

**Comment by Mukul1127** [comment]
https://github.com/Mukul1127/BunnyUnofficialTweak, they are interested in this, maybe will become official?
