### ISSUE TITLE
[Entry]: Revenge

### ISSUE THREAD

**Issue by sehnryr** [Discord-Client-Encyclopedia-Management/Discord3rdparties#131]
### Name

Revenge

### Link

https://github.com/revenge-mod/Revenge

### Features

A modification for the Discord Android app. Continuation of Vendetta. Get it? Vendetta is like, revenging..., yeah.

### Language(s)

TypeScript

### Development Status

Active

### Further comments

> While [Vendetta](https://github.com/vendetta-mod) used to be platform-agnostic, Revenge will only focus on Android as alternatives exist for iOS.
> Focusig on just Android gives us more benefit, as we can add Android-only features more easily.

Status is Active but client cannot be installed yet:
> Installing is not currently possible yet, as we're on the process of moving and renaming things.

**Comment by PalmDevs** [comment]
Revenge's maintainer here. We had change of plans and we plan to continue supporting iOS (although fixes may come slower).

[Installing is now possible both via Vendetta](https://github.com/revenge-mod/Revenge#%EF%B8%8F-installing), although we plan to be completely indepedent from it.

Contributors are actively working to add new features to the fork, but we plan to start a whole new rewrite to improve a lot of things Vendetta hasn't done that well.

**Comment by Mukul1127** [comment]
https://github.com/Mukul1127/RevengeUnofficialTweak, I made this iOS tweak if anyone wants it
