### ISSUE TITLE
Remove the android section

### ISSUE THREAD

**Issue by EnderPlays25** [Discord-Client-Encyclopedia-Management/Discord3rdparties#133]
### Describe your suggestion

There are no Android clients left. Vendetta and Aliucord are discontinued and all the others are cancelled. Just delete the entire section.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Juby210** [comment]
Aliucord is not and I literally made an update 1 day ago, we're focused on maintaining 126.21 Discord version, as it is last usable version in my and other Aliucord contributors eyes.

**Comment by EnderPlays25** [comment]
Problem is there's no mods for new Discord other than the planned Enmity v3 which is NEVER happening

**Comment by Juby210** [comment]
Still why not keep everything for the archive?
