### ISSUE TITLE
[Entry]: Discord for Symbian

### ISSUE THREAD

**Issue by gtrxAC** [Discord-Client-Encyclopedia-Management/Discord3rdparties#147]
### Name

Discord for Symbian

### Link

https://github.com/uwmpr/discord-symbian-fixed

### Features

A Discord client for Symbian^3 devices.

### Language(s)

C++, TypeScript

### Development Status

Active (update: after creating this issue, development on the client has been discontinued)

**Comment by lexyclear** [comment]
@sehnryr you got this.

**Comment by Rico040** [comment]
Repo is unavailable
