### ISSUE TITLE
Development on Feathercord has stopped

### ISSUE THREAD

**Issue by funkdoobeast** [Discord-Client-Encyclopedia-Management/Discord3rdparties#149]
### Describe your suggestion

Sup, was checking through the list earlier. Saw that Feathercord is now considered legacy and development has stopped as of 2024.05.01, wanted to give a heads up.

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by lexyclear** [comment]
ight we got it, 
the last couple issues im giving over to sehnyr
