### ISSUE TITLE
Super Discord

### ISSUE THREAD

**Issue by sehnryr** [Discord-Client-Encyclopedia-Management/Discord3rdparties#15]
## Description

**Name:** Super Discord

**Link:** https://github.com/carlos837/super-discord

**Features:** Super Discord is a universal client modification with many features

**Language(s):** ?

**Development Status:** Active?

## Further comments

The project seems to have been created very recently as there is no code base yet.

**Comment by sehnryr** [comment]
e833dbb69abf270dbecb5557ce99ecda4cb8c536 doesn't close this issue.

Super Discord was labelled as `temporarily-invalid` which means that the mod or client isn't usable yet.

**Comment by saint2706** [comment]
You realise super discord is a scam right?

**Comment by sehnryr** [comment]
> You realise super discord is a scam right?

I didn't thought about the possibility of it being a scam, but now that you said that I can't unsee that. Its features are just more and more weird and improbable, like the one that gives you every badges, or the one that makes you an admin whenever you want.

And as I was searching for evidence, I suspect that the scripts they "created" are from https://github.com/OTAKKATO/ZeroDiscord

I'll close the issue. But when they release a seemingly usable client, I'll add it to the list as a scam, like Bluecord.
