### ISSUE TITLE
[Entry]: DiscordMessanger

### ISSUE THREAD

**Issue by deprecatedbrain** [Discord-Client-Encyclopedia-Management/Discord3rdparties#150]
### Name

DiscordMessanger

### Link

https://github.com/DiscordMessenger/dm

### Features

A Discord client for compatability with older Windows versions.

### Language(s)

C++

### Development Status

Active

**Comment by lexyclear** [comment]
jesus thats some old windows with discord support.
ill add.

**Comment by lexyclear** [comment]
done
