### ISSUE TITLE
[Entry]: LibreDiscord Suggestion

### ISSUE THREAD

**Issue by igetrakks** [Discord-Client-Encyclopedia-Management/Discord3rdparties#152]
### Name

LibreDiscord

### Link

https://gitlab.com/zipdox/librediscord/-/tree/master?ref_type=heads

### Features

LibreDiscord is a free and open source voice and video client for Discord written in C using GTK3 and GLib, Wide Audio API Support.

### Language(s)

C

### Development Status

Active

**Comment by lexyclear** [comment]
added thank you.
