### ISSUE TITLE
[Entry]: Miranda NG Discord Plugin

### ISSUE THREAD

**Issue by MP36ctrl** [Discord-Client-Encyclopedia-Management/Discord3rdparties#153]
### Name

Miranda NG

### Link

https://miranda-ng.org

### Features

Multi Protocol Program that supports Discord

### Language(s)

C/C++

### Development Status

Active

### Further comments

![image](https://github.com/Discord-Client-Encyclopedia-Management/Discord3rdparties/assets/79648510/6e832085-830a-44ca-98de-564018210570)
Proof of miranda supporting Discord

**Comment by lexyclear** [comment]
I generally dont know where to add this, gonna hand this over to the 2nd in command.

**Comment by erkinalp** [comment]
3rd party reimplementations
