### ISSUE TITLE
[Entry]: OpenCord (active fork)

### ISSUE THREAD

**Issue by ThatOneCalculator** [Discord-Client-Encyclopedia-Management/Discord3rdparties#154]
### Name

OpenCord

### Link

https://github.com/topminipie/OpenCord

### Features

Fork of Materii's OpenCord

### Language(s)

Kotlin

### Development Status

Active

**Comment by lexyclear** [comment]
Done, now listed as OpenCord Active Edition. 
Update your githubs readme to follow that.

**Comment by ThatOneCalculator** [comment]
It's not my repo though ^^;

**Comment by ThatOneCalculator** [comment]
...and now it's been deleted after being added 😟

![Screenshot_20240607-094058.png](https://github.com/Discord-Client-Encyclopedia-Management/Discord3rdparties/assets/44733677/8e568579-ebd1-4ab3-acf5-a606beb081b5)
