### ISSUE TITLE
Discord Terminal

### ISSUE THREAD

**Issue by sehnryr** [Discord-Client-Encyclopedia-Management/Discord3rdparties#16]
## Description

**Name:** Discord Terminal

**Link:** https://github.com/atlx/discord-term

**Features:** An extensible Discord terminal client. Can be used with bot or user tokens.

**Language(s):** TypeScript

**Development Status:** On hiatus, since August 2021

## Further comments

The project needs new maintainers.

**Comment by saint2706** [comment]
No.

**Comment by saint2706** [comment]
bro i already added these

**Comment by sehnryr** [comment]
> bro i already added these

I just saw that. But you closed the issues before the commit was done and pushed to main. Next time make sure you first commit and push before closing the issues.
