### ISSUE TITLE
Vesktop Question/Issue

### ISSUE THREAD

**Issue by ShadowCodeX-debug** [Discord-Client-Encyclopedia-Management/Discord3rdparties#163]
### Describe your suggestion

Is Vesktop supposed to be in Mods? I thought it was a Third-Party Reimp...

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by sehnryr** [comment]
3rd party reimps are re-implementations of the discord client using either their API or using a hidden web client to show an interface in a context other than the original, unlike mods which modifies the current web client with custom css and scripts
