### ISSUE TITLE
Bunny has stopped its development as the developer has financial problems

### ISSUE THREAD

**Issue by VaiCaDep0893** [Discord-Client-Encyclopedia-Management/Discord3rdparties#177]
### Describe your suggestion

![ảnh](https://github.com/user-attachments/assets/89e3090f-3ce1-4dc6-b5b2-ab1e7669c934)

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by Xandar-YT** [comment]
There is already a PR, #176, maybe check before posting
