### ISSUE TITLE
Revenge is no longer discontinued

### ISSUE THREAD

**Issue by Purple-EyeZ** [Discord-Client-Encyclopedia-Management/Discord3rdparties#181]
### Describe your suggestion

Revenge is no longer discontinued, development has resumed

https://github.com/revenge-mod/revenge

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by KrystalSkullOfficial** [comment]
Dupe https://github.com/Discord-Client-Encyclopedia-Management/Discord3rdparties/pull/176

**Comment by Purple-EyeZ** [comment]
Will this PR ever be merged?
