### ISSUE TITLE
LemonCord hasn't been updated for a year

### ISSUE THREAD

**Issue by Mukul1127** [Discord-Client-Encyclopedia-Management/Discord3rdparties#182]
### Describe your suggestion

Don't list LemonCord as Active

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by KrystalSkullOfficial** [comment]
Respectfully Lemoncord isnt `Eol`, or `On hiatus`, from the dev themselves "well there wasn't much to update anyways...", "...so yeah it's not on hiatus, just an scarcity of ideas and rust generally being a newer language there's isn't much available atm...", 

![](https://cdn.nest.rip/uploads/36d69f89-bb68-4367-9496-08d0f8169b61.png)
![](https://cdn.nest.rip/uploads/95023dcf-aebb-4dda-bfbb-90d60c56d5d8.png)
![](https://cdn.nest.rip/uploads/68180b94-8946-458f-8314-fa4d5f890e01.png)

however people can open issus's to give them ideas
![](https://cdn.nest.rip/uploads/1871c0cb-7dfb-4561-9d6d-adc0e5cd1adf.png)

**Comment by KrystalSkullOfficial** [comment]
This is the same situation as [Vendroid](https://github.com/Vencord/Vendroid), where it hasn't been updated just because there isn't much todo

**Comment by Mukul1127** [comment]
Ohhhh, ok
