### ISSUE TITLE
GoofCord

### ISSUE THREAD

**Issue by HawkSparrow** [Discord-Client-Encyclopedia-Management/Discord3rdparties#184]
### Name

GoofCord

### Link

https://github.com/Milkshiift/GoofCord

### Features

Highly configurable and privacy-focused Discord client. Based on ArmCord.

### Language(s)

Javascript-Typescript

### Development Status

Active

### Further comments

I will need someone to confirm the language for GoofCord, I belive it to be correct after inspecting codeql.yml on their Git Repo.

**Comment by KrystalSkullOfficial** [comment]
lil vro did not wanna read
its already on the list

![GoofCord]{https://cdn.nest.rip/uploads/e0f9df96-1e4c-49ce-8f0d-7807bf69ef43.png
}
