### ISSUE TITLE
[Entry]: Equidroid

### ISSUE THREAD

**Issue by KaKi87** [Discord-Client-Encyclopedia-Management/Discord3rdparties#188]
### Name

Equidroid

### Link

https://github.com/Equicord/Equidroid

### Features

Fork of Vendroid with extra plugins and features.

### Language(s)

Java, JavaScript

### Development Status

Active

### Further comments

*Features* field placeholder says _**le** description_ instead of _**the** description_. (Are you French — even though the pronoun would still be wrong ?)

---
Thanks

**Comment by lexyclear** [comment]
was told its a joke and not a real client. 
until proven otherwise not adding.

**Comment by KrystalSkullOfficial** [comment]
hello an equicord “dev” here, while Equidriod is real and can be technically used. IT 100% SHOULD NOT BE USED, the only reason we made it was as a joke between me and a different dev *(thororen)*. It is not supported and no support will be given to it. Also there will most likely never have any other commits *(besides the initial ones)* made to it.

**Comment by KaKi87** [comment]
So sad, Vendroid is missing so many plugins 😭
