### ISSUE TITLE
Bluecord is open source

### ISSUE THREAD

**Issue by Senffok** [Discord-Client-Encyclopedia-Management/Discord3rdparties#190]
### Name

Bluecord

### Link

https://github.com/bluemods/Bluecord/

### Features

has built-in plugins, custom themes, supports traffic capture (via Fiddler, etc.)

### Language(s)

Smali, Java, Kotlin

### Development Status

Active

**Comment by KrystalSkullOfficial** [comment]
this has already been cover before https://github.com/Discord-Client-Encyclopedia-Management/Discord3rdparties/issues/81
