### ISSUE TITLE
[Entry]: Purecord

### ISSUE THREAD

**Issue by roundedrectangle** [Discord-Client-Encyclopedia-Management/Discord3rdparties#191]
### Name

Purecord

### Link

https://github.com/Lrdsnow/purecord

### Features

logging in and out, with 2fa (only auth app atm); sending and receiving messages in dms & servers; username colors in servers; nicknames in servers; friend nicknames; viewing emojis; viewing photos; viewing stickers

### Language(s)

Dart, Flutter

### Development Status

Active

### Further comments

The author (lrdsnow) also worked on Purecord-Swift before, but never released it except for a leaked IPA in a Discord server. Then she started to work on the Flutter version instead.

**Comment by roundedrectangle** [comment]
>release build seems to be not working

Strange. It did for me. What platform are you using? You can also contact the developer at the official discord server (I am not the developer): https://discord.gg/cCSwxqdvzx

**Comment by lexyclear** [comment]
does not work
