### ISSUE TITLE
Any plans for making a browser extension list?

### ISSUE THREAD

**Issue by sheesh3178** [Discord-Client-Encyclopedia-Management/Discord3rdparties#193]
### Describe your suggestion

Like Vencord or something?

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by KrstlSkll69** [comment]
The only one is the 

Official:
1. Vencord Web - 
  -   https://chromewebstore.google.com/detail/vencord-web/cbghhgpcnddeihccjmnadmkaejncjndb

2. Shelter -
  -   https://addons.mozilla.org/en-US/firefox/addon/shelter-injector/
  -   https://microsoftedge.microsoft.com/addons/detail/shelter-mv3-inj/okemjpeidkmhjpmdcpaibakdhnheblib

Unofficial 
1. Betterdiscord - (which reviews say doesnt even actually work)
  -   https://chromewebstore.google.com/detail/better-discord-web-unoffi/gdicgodoiikpogmgoihoipfagfcnfcnc
