### ISSUE TITLE
[Entry]: Stossycord

### ISSUE THREAD

**Issue by KrystalSkullOfficial** [Discord-Client-Encyclopedia-Management/Discord3rdparties#200]
### Name

Stossycord

### Link

https://github.com/Stossycord/Stossycord

### Features

Stossycord is a Discord Client Native to iOS Devices. It is made in 100% Swift and SwiftUI for Privacy, Responsiveness and Security

### Language(s)

Swift

### Development Status

Active

**Comment by lexyclear** [comment]
added.
