### ISSUE TITLE
Feature comparission table

### ISSUE THREAD

**Issue by Dave247** [Discord-Client-Encyclopedia-Management/Discord3rdparties#203]
### Describe your suggestion

With so many different mods and also clients out there, it can be hard for a user to be able to determine what exactly does what, especially when compared to other mods/clients or to vanilla Discord itself. For example, when it comes to clients, from my brief searching if they are using [arRPC](https://arrpc.openasar.dev/) as a replacement for rich presence, then there isn't any party support.

Also just listing available platforms, so you can see at a glance what you can actually use, without having to visit each individual link. While some have it mentioned in their descriptions, it's impossible to be properly informative without a separate section for it.

Due to the length of such a table (or multiple tables), it will probably need to have it's separate md file, as the main readme is long enough as it is already. 

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by lexyclear** [comment]
no

**Comment by Dave247** [comment]
Kinda rude. I mean you could at least give a reason, but I guess as it's your guys project then you are free to do with it as you want.
