### ISSUE TITLE
[Entry]: HolyMod by Strencher

### ISSUE THREAD

**Issue by OlavWolfiken** [Discord-Client-Encyclopedia-Management/Discord3rdparties#34]
### Name

HolyMod

### Link

https://github.com/HolyMod/HolyMod

### Features

A lightweight client mod focused on simplicity and performance.

### Language(s)

TypeScript, JavaScript

### Development Status

Discontinued (unmaintained)

### Further comments

On July 16th 2022 Strencher [confirmed that HolyMod isn't maintained anymore](https://discord.com/channels/458997239738793984/925794700563218432/997850188158865458):

![image](https://user-images.githubusercontent.com/50549647/179956803-52a21a6d-64bb-4da7-a5ce-6786978e4a2d.png)

**Comment by lexyclear** [comment]
@sehnryr check
