### ISSUE TITLE
[Entry]: Replugged

### ISSUE THREAD

**Issue by zachjmurphy** [Discord-Client-Encyclopedia-Management/Discord3rdparties#39]
### Name

Replugged

### Link

https://github.com/replugged-org/replugged

### Features

Maintained fork of Powercord

### Language(s)

Javascript

### Development Status

Active

### Further comments

Replugged is a maintained fork of Powercord.

**Comment by sehnryr** [comment]
Thanks for not reading our https://github.com/Discord-Client-Encyclopedia-Management/Discord3rdparties/blob/main/.github/CONTRIBUTING.md

**Comment by zachjmurphy** [comment]
Oh sorry. I didn't see that Replugged was already in the README
