### ISSUE TITLE
Missing clients

### ISSUE THREAD

**Issue by lexyclear** [Discord-Client-Encyclopedia-Management/Discord3rdparties#42]
### Name

clients we should still add

### Link

na

### Features

missing clients

### Language(s)

english

### Development Status

Active

### Further comments

https://github.com/OfficiallySp/FeatherCord
https://github.com/Muunatic/RyU
https://github.com/RoboChimera/ChimeraCord
https://github.com/Velocity-Discord/Velocity

**Comment by NotSpaulding** [comment]
\+ https://github.com/xHyroM/hykord?

**Comment by NotSpaulding** [comment]
> > * https://github.com/xHyroM/hykord?
> 
> @NotSpaulding can you create an issue for that ?

Sorry, thought this was an appropriate place to put this.
Done #43.
