### ISSUE TITLE
End of life notice - Velocity

### ISSUE THREAD

**Issue by CloudRealm** [Discord-Client-Encyclopedia-Management/Discord3rdparties#49]
https://github.com/Velocity-Discord/Velocity/commit/f1e61190bea8b4e5986a229ff3f1ed1012e5bce3

**Comment by sehnryr** [comment]
@CloudRealm what change do you think could be made?

Though the development of their v1.x.x is now end-of-life, they did mention that they're actively working on a v2.

> This update will completely break Velocity v1 and in preparation **development on v2 has already started**.
