### ISSUE TITLE
Special status for client mods that are active but currently broken?

### ISSUE THREAD

**Issue by PixelHir** [Discord-Client-Encyclopedia-Management/Discord3rdparties#54]
Since the previous discord update broke quite a lot client mods, maybe there should be a special status introduced for mods that are actively being worked on but broken? Something like "⚠️Broken/🟢Active"?

**Comment by sehnryr** [comment]
Hi @PixelHir, thanks for the suggestion. We've added an alternative status for Aluicord with :large_blue_circle: to not cause misunderstandings with a :warning: sign that could be misleading.

We already know that many mods broke with the last discord update but we cannot be sure which are and which still works as it would require testing on our side for every one of them. If you know some, you can still open a PR or an issue.
