### ISSUE TITLE
[Entry]: Vencord mobile

### ISSUE THREAD

**Issue by rushiiMachine** [Discord-Client-Encyclopedia-Management/Discord3rdparties#60]
### Name

WebviewCord

### Link

https://github.com/Vencord/Android

### Features

A WebView embedding the Discord site, loading Vencord and adding some fixes for usability.

### Language(s)

Typescript

### Development Status

Active

### Further comments

Intended for Android

**Comment by sehnryr** [comment]
Is this app really named "WebviewCord" ? From what I see, it's just "Vencord" just the mod counterpart.
Feel free to open a Pull Request including this request :) I won't be able to do it right now

**Comment by rushiiMachine** [comment]
> Is this app really named "WebviewCord" ?
i dont think it matters :trollface: 
![image](https://user-images.githubusercontent.com/33725716/211213018-26e5430b-d633-430d-8647-bff843788f47.png)

**Comment by sehnryr** [comment]
> i dont think it matters :trollface:

Well, if we want to include this app to the list, we should use the name of the installed app
