### ISSUE TITLE
Bluecord is Opensource(???)

### ISSUE THREAD

**Issue by ilovethickthighs** [Discord-Client-Encyclopedia-Management/Discord3rdparties#81]
### Describe your suggestion

Correct me if I'm wrong, but didn't Blue make bluecord opensource?

https://github.com/bluemods/Bluecord
Here's the link

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [ ] I have admitted that I am a clown by having checked this box, as I have not read these acknowledgements.
- [X] I will fill out all of the requested information in this form.

**Comment by sehnryr** [comment]
Thank you for providing the information. It appears that Blue has recently made their client open source. However, I'm not sure how to handle the fact that it was previously considered as a malware. Please feel free to open a PR with the revised status of the client
