### ISSUE TITLE
[Suggestion] OpenAsar

### ISSUE THREAD

**Issue by CanadaHonk** [Discord-Client-Encyclopedia-Management/Discord3rdparties#9]
[OpenAsar](https://openasar.dev) (self promo), guess it is a re-implementation and a mod so... welp.

**Comment by lexyclear** [comment]
added

**Comment by sehnryr** [comment]
I think OpenAsar is more a mod than a reimplementation of the client as it is not fully reimplementing the features of Discord.

I've also added a short description for it:

> Alternative app.asar for Discord. Makes your client feel snappier.

If you want to make any change to it, please open a new issue or pull request.
