### ISSUE TITLE
[Entry]: rdircd

### ISSUE THREAD

**Issue by mk-fg** [Discord-Client-Encyclopedia-Management/Discord3rdparties#95]
### Name

reliable-discord-client-irc-daemon

### Link

https://github.com/mk-fg/reliable-discord-client-irc-daemon

### Features

Discord-client to irc-server translation daemon

### Language(s)

Python

### Development Status

Active

### Further comments

For using discord through any IRC client.
I maintain and use it myself, and bunch of other folks seem to have found it too by now, so might as well be on some list.
Though dunno if applicable here, even if technically a discord client, overall it's more like "discord proxy".

Thanks for maintaining the list.

**Comment by lexyclear** [comment]
again no idea how to deal with this one.
Im a leave it for sehnyr
