### ISSUE TITLE
[Entry]: bitlbee-discord

### ISSUE THREAD

**Issue by mk-fg** [Discord-Client-Encyclopedia-Management/Discord3rdparties#96]
### Name

bitlbee-discord

### Link

https://github.com/sm00th/bitlbee-discord

### Features

Plugin for an old any-IM-to-IRC translation/proxy "bitlbee" daemon

### Language(s)

C

### Development Status

Active

### Further comments

Can be used from any IRC client.
Seem to be working and bunch of people mention various issues in it from time to time in #bitlbee irc channel (most recent one ~20d ago), even if repo doesn't look very active.
Same caveat as with other rdircd suggestion - not sure if list has section for such "client proxies".

Thanks for maintaining this list.

**Comment by lexyclear** [comment]
So its a plugin builder> or? Im a leave this one for Sehnyr

**Comment by TheLastZombie** [comment]
BitlBee is kind of a framework that enables users to bridge different services (including, with this plugin, Discord) to IRC. As such I believe it would fall into the same category as purple-discord.
