### ISSUE TITLE
[Entry]: Discross

### ISSUE THREAD

**Issue by hqnt** [Discord-Client-Encyclopedia-Management/Discord3rdparties#98]
### Name

Discross

### Link

http://discross.rc24.xyz/index.html

### Features

A work-in-progress unofficial Discord relay (that acts like a client) aiming to support all platforms that support HTML. It uses webhooks and a bot so it doesn't need your user token, which would allow anyone to control your account. However, this means it only works on servers with the bot. 

### Language(s)

HTML

### Development Status

Active

### Further comments

What platforms are supported?

Virtually anything, although you may not get all features. Platforms that are confirmed to work, to some extent:
--

<font face="Arial, Helvetica, sans-serif" color="#dddddd" style="font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none; background-color: rgb(48, 51, 56);"><ul><li>Nintendo 3DS</li><li>Nintendo DS</li><li>Nintendo DSi</li><li>Nintendo Switch (requires a workaround to access the web browser)</li><li>PlayStation 3</li><li>PlayStation 4</li><li>PlayStation Portable</li><li>PlayStation Vita</li><li>Sega Dreamcast</li><li>TiVo (via EnterWebz)</li><li>Wii Internet Channel</li><li>Wii U</li><li>Windows 95/98</li><li>Xbox 360</li></ul><font size="3" face="Arial, Helvetica, sans-serif" color="#aaaaaa"></font></font><br class="Apple-interchange-newline" style="caret-color: rgb(0, 0, 0); color: rgb(0, 0, 0); font-style: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: auto; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-tap-highlight-color: rgba(26, 26, 26, 0.3); -webkit-text-size-adjust: auto; -webkit-text-stroke-width: 0px; text-decoration: none;"><br class="Apple-interchange-newline">

**Comment by lexyclear** [comment]
idk how to do this one tbh. why i set it for sehnyr.
